###############################################################
# IMPORTS
###############################################################

import random
import periodic_table as pt




###############################################################
# INITIALIZE VARIABLES
###############################################################

Name, Number, Mass = {}, {}, {}
score = 0

for element in pt.ELEMENTS_DATA:
    Name[element] = pt.ELEMENTS_DATA[str(element)]["name"]  # Initialize symbols and names (dict)
for element in pt.ELEMENTS_DATA:
    Mass[element] = pt.ELEMENTS_DATA[str(element)]["atomic-mass"]  # Initialize symbols and atomic mass (dict)
for i in range(1, 119):
    Number[i] = list(Name.values())[i-1]  # Initialize symbol and atomic number (dict)




###############################################################
# FUNCTIONS
###############################################################

def GenerateQuiz():  # A function to generate a random quiz
    global score
    
    pattern = random.choice([0, 1])  # Randomly choose question pattern 
    ques_symb, ques_name = None, None
    
    if pattern == 1:
        ques_symb = random.choice(list(Name.keys()))  # Take a random symbol
        ans = input("\nWhat is the name of the element " + ques_symb + "?\nAnswer: ")  # Take name as input

        if ans.strip().capitalize() == list(Name.values())[list(Name.keys()).index(ques_symb)]:  # Check if answer is correct
            print(" Congrats!")  # Increase score by 1
            score += 1
        else:
            print(" Failed!")

    elif pattern == 0:
        ques_name = random.choice(list(Name.values()))  # Take a random name
        ans = input("\nWhat is the symbol of " + ques_name + "?\nAnswer: ")  # Take symbol as input

        if ans.strip().capitalize() == list(Name.keys())[list(Name.values()).index(ques_name)]:  # Check if answer is correct
            print(" Congrats!")
            score += 1  # Increase score by 1
        else:
            print(" Failed!")


def Ask(times):  # A function to ask quizes generated by GenerateQuiz()
    global score
    
    totalScore = times  # Total score should be equal to the number total qustion
    for _ in range(times):
        GenerateQuiz()  # Ask question as many times as asked

    print("\n\nYour Score is " + str(score) + "/" + str(totalScore))  # Print the score




###############################################################
# MAIN
###############################################################

Ask(5)
